def main():
    try:
        print(3/0)
    except Exception as ex:
        print(ex)